id: I2444A82A
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T04:19:10.202816'
last_modified: '2022-06-19T04:19:10.202829'
parser: null
source_metadata:
  title: Supplement to the History of the Abbots of Ngor E waṃ chos ldan; Lamdre Tshogshe,
    vol. ya, title no. 5
  author: དཔལ་ལྡན་ཆོས་སྐྱོང་།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-12);
    pagination incomplete (pp. 596-651), unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/590
  bases:
    62c8:
      title: Supplement to the History of the Abbots of Ngor E waṃ chos ldan; Lamdre
        Tshogshe, vol. ya, title no. 5
      order: 1
      base_file: 62c8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
